[advisories]
ignore = []
informational_warnings = ["unmaintained"]
severity_threshold = "low"

[output]
deny = ["unmaintained"]
format = "terminal"
quiet = false
show_tree = true

[yanked]
enabled = true
update_index = false
